### ISSUE TITLE
aoe2dat in "bin"

### ISSUE THREAD

**Issue by einstein95** [HSZemi/aoe2dat#1]
From [README.md](https://github.com/HSZemi/aoe2dat/blob/master/README.md)
> `bin` contains a compiled version of above code for linux - no idea if it will work or even execute on another machine

This indeed doesn't run out of the box as was dynamically linked (not statically) and requires `libgenieutils.so` from https://github.com/sandsmark/genieutils.

The result of running `ldd aoe2dat`:
```
linux-vdso.so.1 (0x00007fffd7be7000)
libgenieutils.so => not found
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007ff9b0515000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007ff9b04fb000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007ff9b0334000)
libm.so.6 => /usr/lib/libm.so.6 (0x00007ff9b01ee000)
/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007ff9b0961000)
```

**Comment by HSZemi** [comment]
The situation should have improved significantly with a8815c9d41c3edbaed728d1c05c732e5af926be9
