### ISSUE TITLE
Would it be possible to include the Graphics data as well?

### ISSUE THREAD

**Issue by willemmulder** [HSZemi/aoe2dat#3]
I'm trying to calculate the Frame Delay in seconds for any given unit, and it appears I need the "Frames per Angle" and "Anim Duration" for the relevant animations. See e.g. https://www.reddit.com/r/aoe2/comments/eg0619/my_research_on_how_frame_delay_works/ or https://ageofempires.fandom.com/wiki/Frame_delay for more info on how that works. 

I can find the relevant details in the Genie editor under the 'Graphics' tab. However I cannot find any Graphics related information in the full.json. Is there any chance that this could be added?

Thanks!

**Comment by HSZemi** [comment]
Hmm, possibly. There are some things in `src/genie/dat/Graphics.h` that look like what you need…

**Comment by HSZemi** [comment]
It looks like the `DatFile` structure just contains a list of `Graphic` elements. That means that you probably need more information to match the `Graphic` items to e.g. units. Any idea how that is done? :thinking:

**Comment by willemmulder** [comment]
Hmm, for what I know we can find e.g. the attack graphic in a unit at `Type50.AttackGraphic`. For an archer that would be graphic 627. If I look at the Graphics tab, that's a huge list with 12303 items, where the one with number/ID 627 (the list is 0-based) would be the Graphic with Internal Name "Archer (Attack)". Does that help anything?

**Comment by HSZemi** [comment]
You tell me :wink: 
3a69655283139841599e868ecaec5a01a6a1205a

**Comment by willemmulder** [comment]
Yes that works! Thanks for making this work, and especially for making it work so quickly :-D
