### ISSUE TITLE
Work Rate availability

### ISSUE THREAD

**Issue by dariomangoni** [HSZemi/aoe2dat#4]
More a question than an issue: I can't find the Work Rate information regarding neither Units (Villagers, to be more precise) nor Buildings (Farms, Fish, etc).

Is there a way to retrieve it?
Is the actual gathering rate the multiplication by unit.WorkRate*farm.WorkRate?

Thanks for any suggestion

**Comment by HSZemi** [comment]
There is a workrate value in `Units[index]->Bird->WorkRate`, maybe that is the value you are looking for?

Regarding the workrate of farmers, as far as I know the workrate of the farm determines how quickly the farm generates food that can be harvested by a farmer, while the farmer's workrate determines how quickly it can gather food from a farm.
In conclusion this means that the actual gathering rate on farms is the minimum of the farm's and the farmer's work rates.
If I recall correctly, this meant that the Slav's farming bonus was actually capped below its theoretical limit when it was introduced, and also the reason why farmers were still very slow when you activated `aegis` (until DE fixed that).

**Comment by dariomangoni** [comment]
Oh that's exactly what I wanted to know.
Farming is the only situation in which both the Building and the gathering Units have a Work Rate value in the tables.

- Farm (ID:50, Building) Work Rate: 0.4 ---> colture on the ground
- Farmer (ID:214, Units) Work Rate: 0.53 --> Villager in the farming role

While for any other food source, the **source itself** has no Work Rate (Fish, Bush, any Herdable)
while **only the Villagers** in the different role (Fisherman, Forager, Hunter)
have different Work Rate (0.43, 0.31, 0.41 respectively).

I tried with a custom scenario and it is clear that the true gathering rate (excluding seeding and walking time) it is 0.4, so the min() it is probably applied.

Thanks a lot!
